### PR TITLE
Add Discord Invite SVG Badge to README

### PR DESCRIPTION
**Pull request by smritics**
### Changes
- [ ] Added/updated scripts or configurations.
- [ ] Remove Bad Script/Code.
- [ ] Fixed issue #[issue number].
- [x] Improved/optimized existing functionality.
- [ ] Bugs Fixes.
- [ ] Feature Added.
- [ ] UI Enhancement.
- [ ] Scripts ZIP
- [x] Documentation

### Checklist

Please ensure your pull request meets the following requirements:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes do not introduce new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by aayushrg7 — APPROVED** [review]

**Comment by harilvfs** [comment]
@smritics yesko need xa jasto lagdena malai yetikai ni thek xatw

**Comment by harilvfs** [comment]
@harilvfs 


double lage hola timilai tara mathi ko discord ko badge hatayera yelai rakheko hoo

**Comment by smritics** [comment]
double lage hola timilai tara mathi ko discord ko badge hatayera yelai rakheko hoo

**Comment by harilvfs** [comment]
@smritics thank you!!!

**Review by harilvfs — APPROVED** [review]

**Pull request merged**
