### PR TITLE
Enhanced README with Catppuccin-themed badges

### PR DESCRIPTION
**Pull request by smritics**
### Changes
- [x] Updates 
- [ ] Remove 
- [ ] Fixed issue #[issue number].
- [x] Improved 
- [ ] Fixes.
- [ ] Feature 
- [ ] UI/UX 
- [ ] ZIP 
- [ ] Documentation

### CODE REVIEW

**Comment by aayushrg7** [comment]
@smritics my god yeti dherai commits 😲

**Review by aayushrg7 — APPROVED** [review]

**Comment by smritics** [comment]
@aayushrg7 Github Bata Jo Changes Gareko Vayera Yeti Dheari Vako

**Comment by harilvfs** [comment]
@smritics preview?

**Comment by harilvfs** [comment]
@smritics nice

**Review by harilvfs — APPROVED** [review]

**Pull request merged**
